package com.revature.passwordmanager.controller;

import com.revature.passwordmanager.dto.request.ChatRequest;
import com.revature.passwordmanager.dto.response.AIInsightResponse;
import com.revature.passwordmanager.dto.response.ChatResponse;
import com.revature.passwordmanager.dto.response.MessageResponse;
import com.revature.passwordmanager.service.ai.AIAssistantService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

/**
 * Feature 41 – AI Password Assistant.
 *
 * <p>Base URL: {@code /api/ai}</p>
 *
 * <p>All endpoints require authentication. When an OpenAI API key is configured
 * ({@code ai.openai.api-key}), responses are generated by GPT-3.5-turbo.
 * Without a key, a rule-based fallback provides deterministic responses.</p>
 */
@RestController
@RequestMapping("/api/ai")
@RequiredArgsConstructor
@Tag(name = "AI Password Assistant", description = "Feature 41 – AI-powered password security assistant")
public class AIAssistantController {

    private final AIAssistantService assistantService;

    @Operation(
        summary = "Send a message to the AI assistant",
        description = "Sends a natural language message and receives an AI response. " +
                      "Maintains conversation history per user session. " +
                      "Automatically detects intent (GENERATE_PASSWORD, SECURITY_ANALYSIS, etc.) " +
                      "and includes a generated password when relevant."
    )
    @PostMapping("/chat")
    public ResponseEntity<ChatResponse> chat(@Valid @RequestBody ChatRequest request) {
        return ResponseEntity.ok(assistantService.chat(getCurrentUsername(), request));
    }

    @Operation(
        summary = "Get contextual suggestions",
        description = "Returns quick-action suggestions based on the user's current vault state " +
                      "(e.g., 'Update 3 passwords older than 90 days')."
    )
    @GetMapping("/suggestions")
    public ResponseEntity<ChatResponse> getSuggestions() {
        return ResponseEntity.ok(assistantService.getSuggestions(getCurrentUsername()));
    }

    @Operation(
        summary = "Generate a contextual password with AI explanation",
        description = "Generates a strong password and provides an AI-generated explanation. " +
                      "Optionally provide context (e.g., 'for my bank account') via the ?context param."
    )
    @PostMapping("/generate-password")
    public ResponseEntity<ChatResponse> generatePassword(
            @Parameter(description = "Optional context for the password (e.g., 'for my bank account')")
            @RequestParam(required = false) String context) {
        return ResponseEntity.ok(assistantService.generatePassword(getCurrentUsername(), context));
    }

    @Operation(
        summary = "Get AI security insights for the vault",
        description = "Analyzes the user's vault and returns actionable security recommendations " +
                      "with severity levels (CRITICAL, HIGH, MEDIUM, LOW, INFO) and an overall score."
    )
    @GetMapping("/security-insights")
    public ResponseEntity<AIInsightResponse> getSecurityInsights() {
        return ResponseEntity.ok(assistantService.getSecurityInsights(getCurrentUsername()));
    }

    @Operation(
        summary = "Clear chat history",
        description = "Deletes the user's entire conversation history with the AI assistant."
    )
    @DeleteMapping("/session")
    public ResponseEntity<MessageResponse> clearSession() {
        assistantService.clearSession(getCurrentUsername());
        return ResponseEntity.ok(new MessageResponse("Chat history cleared successfully"));
    }

    private String getCurrentUsername() {
        return SecurityContextHolder.getContext().getAuthentication().getName();
    }
}
